name: news_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  provider: ^6.1.4
  http: ^1.3.0
  flutter_spinkit: ^5.2.1
  cupertino_icons: ^1.0.8
  share_plus: ^11.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  timeago: ^3.7.1
  url_launcher: ^6.3.1
  intl: ^0.20.2
  shared_preferences: ^2.5.3
  audioplayers: ^6.4.0
  flutter_switch: ^0.3.2


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.5

flutter:

  assets:
    - images/
    - assets/
  uses-material-design: true

  fonts:
   - family: LibreBaskerville
     fonts:
       - asset: fonts/LibreBaskerville-Regular.ttf
